context:
  version: "0.4.0"

package:
  name: cchecksum
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/c/cchecksum/cchecksum-${{ version }}.tar.gz
  sha256: 8b1caac10a5462d199af3800da1e419a1678d3c0febca85eaf29196bbf2573cb

build:
  script: ${{ PYTHON }} -m pip install . --ignore-installed --no-cache-dir --no-deps -vv
  number: 0

requirements:
  build:
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
  host:
    - Cython >=3.2.3
    - python
    - pip
    - setuptools
    - setuptools_scm
  run:
    - eth-hash
    - eth-typing
    - safe-pysha3 >=1.0.0
    - python

tests:
  - python:
      imports:
        - cchecksum
      pip_check: true

  - script:
      - pytest tests
    requirements:
      run:
        - eth-utils >=5.3.1
        - pytest >=8,<10
        - python
        - web3 >=7.14.0
    files:
      source:
        - tests/

about:
  homepage: https://github.com/BobTheBuidler/cchecksum
  summary: 'A ~8x faster drop-in replacement for eth_utils.to_checksum_address'
  description: |
    CChecksum is a ~8x faster drop-in replacement for eth_utils.to_checksum_address,
    with the most cpu-intensive part implemented in C.
    It keeps the exact same API as the existing implementation, exceptions and all.
  license: MIT
  license_file: LICENSE
  documentation: https://bobthebuidler.github.io/cchecksum/
  repository: https://github.com/BobTheBuidler/cchecksum

extra:
  recipe-maintainers:
    - MementoRC
